### ISSUE TITLE
Google search results for AutoHotKey lead to dead end

### ISSUE THREAD

**Issue by SamHasler** [ahkscript/ahkscript.github.io#10]
Sorry if this is the wrong place to file this but you appear to be in the middle of a re-org and it's _very_ confusing.

Searching google for autohotkey solutions to problems often leads to the old forums which appear to be unaccessable. e.g.:

The 4th result in the Google Search for [[autohotkey esc "caps lock" ctrl](https://www.google.co.uk/search?q=autohotkey+esc+"caps+lock"+ctrl)] is:
https://autohotkey.com/board/topic/104173-capslock-to-control-and-escape/
Which shows an error page with the message:

>   Sorry, you don't have permission for that!
> 
>   You are not allowed to visit this community.

Clicking the "Create Account" link shows the same message! And so does clicking Sign In > I've forgotten my password.

**Comment by rshipp** [comment]
There is some information about this [here](http://ahkscript.org/foundation/history.html). The short version is, don't use autohotkey.com; use [ahkscript.org](http://ahkscript.org) instead.

**Comment by ttnnkkrr** [comment]
could you send me a screen shot of this message?
I am able to visit the link below even after logging out. and able to log on.


From: Sam Hasler 
Sent: Monday, November 23, 2015 6:42 AM
To: ahkscript/ahkscript.github.io 
Subject: [ahkscript.github.io] Google search results for AutoHotKey lead to dead end (#10)

Sorry if this is the wrong place to file this but you appear to be in the middle of a re-org and it's very confusing.

Searching google for autohotkey solutions to problems often leads to the old forums which appear to be unaccessable. e.g.:

The 4th result in the Google Search for [autohotkey esc "caps lock" ctrl] is:
https://autohotkey.com/board/topic/104173-capslock-to-control-and-escape/
Which shows an error page with the message:

  Sorry, you don't have permission for that!

  You are not allowed to visit this community.

Clicking the "Create Account" link shows the same message! And so does clicking Sign In > I've forgotten my password.

**Comment by rshipp** [comment]
https://web.archive.org/web/20150505005207/http://www.autohotkey.com/board/topic/104173-capslock-to-control-and-escape/

**Comment by ttnnkkrr** [comment]
seems I may have spoken too soon my login failed.
it may perhaps be due to the expired license on this forum software

From: Sam Hasler 
Sent: Monday, November 23, 2015 6:42 AM
To: ahkscript/ahkscript.github.io 
Subject: [ahkscript.github.io] Google search results for AutoHotKey lead to dead end (#10)

Sorry if this is the wrong place to file this but you appear to be in the middle of a re-org and it's very confusing.

Searching google for autohotkey solutions to problems often leads to the old forums which appear to be unaccessable. e.g.:

The 4th result in the Google Search for [autohotkey esc "caps lock" ctrl] is:
https://autohotkey.com/board/topic/104173-capslock-to-control-and-escape/
Which shows an error page with the message:

  Sorry, you don't have permission for that!

  You are not allowed to visit this community.

Clicking the "Create Account" link shows the same message! And so does clicking Sign In > I've forgotten my password.

**Comment by SamHasler** [comment]
This is what I see:

![autohotkey](https://cloud.githubusercontent.com/assets/54277/11363781/e0d57b20-9293-11e5-8ae1-c5fe533f3e8b.png)

**Comment by joedf** [comment]
I think it's something else. From the IPB website:
> License Renewals
------------------------------
Our self-hosted licenses renew on a six-month basis, and provide ongoing access to support, software and services. If you do not renew by your expiration date, your software will continue to function. However, support, software downloads and additional services will be unavailable until you renew.

**Comment by joedf** [comment]
Dead issue.
